version: "3.9"

services:

  redis-cluster:
    image: "redis:alpine"
    network_mode: "host"
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    command:
      redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 --cluster-replicas 1 --cluster-yes

  redis-node-0:
    image: "redis:alpine"
    network_mode: "host"
    volumes:
      - ./redis-cluster-test/7000/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-node-1:
    image: "redis:alpine"
    network_mode: "host"
    volumes:
      - ./redis-cluster-test/7001/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-node-2:
    image: "redis:alpine"
    network_mode: "host"
    volumes:
      - ./redis-cluster-test/7002/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-node-3:
    image: "redis:alpine"
    network_mode: "host"
    volumes:
      - ./redis-cluster-test/7003/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-node-4:
    image: "redis:alpine"
    network_mode: "host"
    volumes:
      - ./redis-cluster-test/7004/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-node-5:
    image: "redis:alpine"
    network_mode: "host"
    volumes:
      - ./redis-cluster-test/7005/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf